
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1111
    url: jdbc:mysql://127.0.0.1:3306/myproject
  velocity:
    charset: UTF-8
    suffix: .html
    resource-loader-path: classpath:/templates/
